"use client"

import * as SiIcons from "react-icons/si"
import * as FaIcons from "react-icons/fa"
import { Box } from "lucide-react"

// Map app names to react-icons component names (can be from Si or Fa)
const appIconMap: Record<string, { set: "si" | "fa"; name: string }> = {
  "Google Drive": { set: "si", name: "SiGoogledrive" },
  "Gmail": { set: "si", name: "SiGmail" },
  "Google Sheets": { set: "si", name: "SiGooglesheets" },
  "Google Docs": { set: "si", name: "SiGoogledocs" },
  "Google Calendar": { set: "si", name: "SiGooglecalendar" },
  "Google Chat": { set: "si", name: "SiGooglechat" },
  "Google Vertex AI": { set: "si", name: "SiGooglecloud" },
  "Google Workspace": { set: "si", name: "SiGoogle" },
  "Outlook": { set: "fa", name: "FaMicrosoft" },
  "Excel": { set: "fa", name: "FaFileExcel" },
  "SharePoint": { set: "fa", name: "FaMicrosoft" },
  "Microsoft Teams": { set: "fa", name: "FaMicrosoft" },
  "OneDrive": { set: "fa", name: "FaMicrosoft" },
  "Power BI": { set: "si", name: "SiPowerbi" },
  "Azure Blob Storage": { set: "fa", name: "FaMicrosoft" },
  "Azure SQL": { set: "fa", name: "FaMicrosoft" },
  "Azure OpenAI": { set: "si", name: "SiOpenai" },
  "Synapse": { set: "fa", name: "FaMicrosoft" },
  "Notion": { set: "si", name: "SiNotion" },
  "HubSpot": { set: "si", name: "SiHubspot" },
  "Dropbox": { set: "si", name: "SiDropbox" },
  "Box": { set: "si", name: "SiBox" },
  "Jira": { set: "si", name: "SiJira" },
  "Confluence": { set: "si", name: "SiConfluence" },
  "Linear": { set: "si", name: "SiLinear" },
  "Asana": { set: "si", name: "SiAsana" },
  "Clickup": { set: "si", name: "SiClickup" },
  "Github": { set: "si", name: "SiGithub" },
  "Slack": { set: "si", name: "SiSlack" },
  "Intercom": { set: "si", name: "SiIntercom" },
  "Salesforce": { set: "si", name: "SiSalesforce" },
  "Stripe": { set: "si", name: "SiStripe" },
  "Shopify": { set: "si", name: "SiShopify" },
  "Zapier": { set: "si", name: "SiZapier" },
  "Make": { set: "si", name: "SiMake" },
  "MongoDB": { set: "si", name: "SiMongodb" },
  "PostgreSQL": { set: "si", name: "SiPostgresql" },
  "MySQL": { set: "si", name: "SiMysql" },
  "Oracle": { set: "si", name: "SiOracle" },
  "Oracle Database": { set: "si", name: "SiOracle" },
  "Elasticsearch": { set: "si", name: "SiElasticsearch" },
  "Snowflake": { set: "si", name: "SiSnowflake" },
  "Databricks": { set: "si", name: "SiDatabricks" },
  "BigQuery": { set: "si", name: "SiGooglebigquery" },
  "AWS S3": { set: "si", name: "SiAmazons3" },
  "AWS Bedrock": { set: "si", name: "SiAmazonaws" },
  "AWS SQS": { set: "si", name: "SiAmazonaws" },
  "OpenAI": { set: "si", name: "SiOpenai" },
  "Anthropic": { set: "si", name: "SiAnthropic" },
  "Perplexity": { set: "si", name: "SiPerplexity" },
  "Groq": { set: "si", name: "SiGroq" },
  "Replicate": { set: "si", name: "SiReplicate" },
  "Together AI": { set: "si", name: "SiTogetherai" },
  "Mistral AI": { set: "si", name: "SiMistral" },
  "XAI": { set: "si", name: "SiX" },
  "YouTube": { set: "si", name: "SiYoutube" },
  "LinkedIn": { set: "si", name: "SiLinkedin" },
  "Hightouch": { set: "si", name: "SiHightouch" },
  "Loom": { set: "si", name: "SiLoom" },
  "Looker": { set: "si", name: "SiLooker" },
  "MCP": { set: "si", name: "SiMcp" },
  "Miro": { set: "si", name: "SiMiro" },
  "NetSuite": { set: "si", name: "SiNetsuite" },
  "Outreach": { set: "si", name: "SiOutreach" },
  "PandaDoc": { set: "si", name: "SiPandadoc" },
  "Perplexity": { set: "si", name: "SiPerplexity" },
  "Pinecone": { set: "si", name: "SiPinecone" },
  "PitchBook": { set: "si", name: "SiPitchbook" },
  "Plaid": { set: "si", name: "SiPlaid" },
  "Polygon": { set: "si", name: "SiPolygon" },
  "PostgreSQL": { set: "si", name: "SiPostgresql" },
  "Power BI": { set: "si", name: "SiPowerbi" },
  "Realtime Chat": { set: "si", name: "SiRealtimechat" },
  "Reducto": { set: "si", name: "SiReducto" },
  "Replicate": { set: "si", name: "SiReplicate" },
  "RunwayML": { set: "si", name: "SiRunway" },
  "Salesforce": { set: "si", name: "SiSalesforce" },
  "Sap": { set: "si", name: "SiSap" },
  "SerpAPI": { set: "si", name: "SiSerpapi" },
  "Servicenow": { set: "si", name: "SiServicenow" },
  "Smartsheet": { set: "si", name: "SiSmartsheet" },
  "Snowflake": { set: "si", name: "SiSnowflake" },
  "Stripe": { set: "si", name: "SiStripe" },
  "Synapse": { set: "fa", name: "FaMicrosoft" },
  "Together AI": { set: "si", name: "SiTogetherai" },
  "Typeform": { set: "si", name: "SiTypeform" },
  "Veeva": { set: "si", name: "SiVeeva" },
  "Weaviate": { set: "si", name: "SiWeaviate" },
  "Wolfram Alpha": { set: "si", name: "SiWolframmathematica" },
  "Workable": { set: "si", name: "SiWorkable" },
  "Workday": { set: "si", name: "SiWorkday" },
  "XAI": { set: "si", name: "SiX" },
  "Yahoo Finance": { set: "si", name: "SiYahoo" },
  "YouTube": { set: "si", name: "SiYoutube" },
  "Zapier": { set: "si", name: "SiZapier" },
  "Zendesk": { set: "si", name: "SiZendesk" },
  "Algolia": { set: "si", name: "SiAlgolia" },
  "AppFolio": { set: "si", name: "SiAppfolio" },
  "Ashby": { set: "si", name: "SiAshby" },
  "Braze": { set: "si", name: "SiBraze" },
  "Cerebras": { set: "si", name: "SiCerebras" },
  "Coda": { set: "si", name: "SiCoda" },
  "Crunchbase": { set: "si", name: "SiCrunchbase" },
  "Databricks": { set: "si", name: "SiDatabricks" },
  "DealCloud": { set: "si", name: "SiDealcloud" },
  "Dovetail": { set: "si", name: "SiDovetail" },
  "DuckDuckGo": { set: "si", name: "SiDuckduckgo" },
  "E2B": { set: "si", name: "SiE2b" },
  "Elasticsearch": { set: "si", name: "SiElasticsearch" },
  "Epic FHIR": { set: "si", name: "SiEpic" },
  "Exa AI": { set: "si", name: "SiExa" },
  "Extend": { set: "si", name: "SiExtend" },
  "Fathom": { set: "si", name: "SiFathom" },
  "Firecrawl": { set: "si", name: "SiFirecrawl" },
  "Fred": { set: "si", name: "SiFred" },
  "Glean": { set: "si", name: "SiGlean" },
  "Groq": { set: "si", name: "SiGroq" },
  "HubSpot": { set: "si", name: "SiHubspot" },
  "Intercom": { set: "si", name: "SiIntercom" },
  "Jira": { set: "si", name: "SiJira" },
  "Linear": { set: "si", name: "SiLinear" },
  "LinkedIn": { set: "si", name: "SiLinkedin" },
  "Loom": { set: "si", name: "SiLoom" },
  "Looker": { set: "si", name: "SiLooker" },
  "MCP": { set: "si", name: "SiMcp" },
  "Microsoft Teams": { set: "fa", name: "FaMicrosoft" },
  "Miro": { set: "si", name: "SiMiro" },
  "Mistral AI": { set: "si", name: "SiMistral" },
  "MongoDB": { set: "si", name: "SiMongodb" },
  "MySQL": { set: "si", name: "SiMysql" },
  "NetSuite": { set: "si", name: "SiNetsuite" },
  "Notion": { set: "si", name: "SiNotion" },
  "OneDrive": { set: "fa", name: "FaMicrosoft" },
  "OpenAI": { set: "si", name: "SiOpenai" },
  "Oracle": { set: "si", name: "SiOracle" },
  "Oracle Database": { set: "si", name: "SiOracle" },
  "Outlook": { set: "fa", name: "FaMicrosoft" },
  "Outreach": { set: "si", name: "SiOutreach" },
  "PandaDoc": { set: "si", name: "SiPandadoc" },
  "Perplexity": { set: "si", name: "SiPerplexity" },
  "Pinecone": { set: "si", name: "SiPinecone" },
  "PitchBook": { set: "si", name: "SiPitchbook" },
  "Plaid": { set: "si", name: "SiPlaid" },
  "Polygon": { set: "si", name: "SiPolygon" },
  "PostgreSQL": { set: "si", name: "SiPostgresql" },
  "Power BI": { set: "si", name: "SiPowerbi" },
  "Realtime Chat": { set: "si", name: "SiRealtimechat" },
  "Reducto": { set: "si", name: "SiReducto" },
  "Replicate": { set: "si", name: "SiReplicate" },
  "RunwayML": { set: "si", name: "SiRunway" },
  "Salesforce": { set: "si", name: "SiSalesforce" },
  "Sap": { set: "si", name: "SiSap" },
  "SEC EDGAR": { set: "si", name: "SiSecedgar" },
  "SerpAPI": { set: "si", name: "SiSerpapi" },
  "Servicenow": { set: "si", name: "SiServicenow" },
  "Shopify": { set: "si", name: "SiShopify" },
  "Smartsheet": { set: "si", name: "SiSmartsheet" },
  "Snowflake": { set: "si", name: "SiSnowflake" },
  "S&P Global": { set: "si", name: "SiSandpglobal" },
  "Stripe": { set: "si", name: "SiStripe" },
  "Synapse": { set: "fa", name: "FaMicrosoft" },
  "Together AI": { set: "si", name: "SiTogetherai" },
  "Typeform": { set: "si", name: "SiTypeform" },
  "Veeva": { set: "si", name: "SiVeeva" },
  "Weaviate": { set: "si", name: "SiWeaviate" },
  "Wolfram Alpha": { set: "si", name: "SiWolframmathematica" },
  "Workable": { set: "si", name: "SiWorkable" },
  "Workday": { set: "si", name: "SiWorkday" },
  "XAI": { set: "si", name: "SiX" },
  "Yahoo Finance": { set: "si", name: "SiYahoo" },
  "YouTube": { set: "si", name: "SiYoutube" },
  "Zapier": { set: "si", name: "SiZapier" },
  "Zendesk": { set: "si", name: "SiZendesk" },
}

interface AppIconProps {
  appName: string
  className?: string
}

export default function AppIcon({ appName, className = "w-3.5 h-3.5" }: AppIconProps) {
  const iconConfig = appIconMap[appName]
  
  if (!iconConfig) {
    return <Box className={className} />
  }
  
  const IconComponent = iconConfig.set === "si" 
    ? SiIcons[iconConfig.name as keyof typeof SiIcons]
    : FaIcons[iconConfig.name as keyof typeof FaIcons]
  
  if (!IconComponent) {
    return <Box className={className} />
  }
  
  // Simple Icons should render with their brand colors by default
  // The icon component should preserve its natural colors
  return <IconComponent className={className} />
}
